import 'rxjs/Subject';
import 'rxjs/Observable';
import 'rxjs/Subscription';
import 'rxjs/BehaviorSubject';
import 'rxjs/add/observable/of';
import 'rxjs/add/observable/fromPromise';
// import 'rxjs/add/observable/throw';
import 'rxjs/add/operator/catch';
import 'rxjs/add/operator/combineLatest';
import 'rxjs/add/operator/filter';
// import 'rxjs/add/operator/finally';
import 'rxjs/add/operator/map';
// import 'rxjs/add/operator/mergeMap';
// import 'rxjs/add/operator/switchMap';
// import 'rxjs/add/operator/takeWhile';
